# Generated by Django 3.2.12 on 2022-03-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="internal_job_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
